import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:sample_app/core/enums.dart';
import 'package:sample_app/core/providers.dart';
import 'package:sample_app/features/attendance/data/repositories/attendance_repository_impl.dart';
import 'package:sample_app/features/attendance/data/sources/attendance_remote_data_source.dart';
import 'package:sample_app/features/attendance/domain/entities/attendance.dart';
import 'package:sample_app/features/attendance/domain/repositories/attendance_repository.dart';

final attendanceRemoteDataSourceProvider = Provider<AttendanceRemoteDataSource>((ref) {
  final firestoreService = ref.watch(firestoreServiceProvider);
  return AttendanceRemoteDataSourceImpl(firestoreService);
});

final attendanceRepositoryProvider = Provider<AttendanceRepository>((ref) {
  final remoteDataSource = ref.watch(attendanceRemoteDataSourceProvider);
  return AttendanceRepositoryImpl(remoteDataSource: remoteDataSource);
});

final attendanceStreamProvider = StreamProvider<List<AttendanceRecord>>((ref) {
  final repository = ref.watch(attendanceRepositoryProvider);
  return repository.getAttendanceStream();
});

class AttendanceController {
  final Ref _ref;
  final AttendanceRepository _repository;

  AttendanceController(this._ref, this._repository);

  Future<void> markAttendance(String staffId, DateTime date, AttendanceStatus status) async {
    final normalizedDate = DateTime(date.year, date.month, date.day);
    final allRecords = _ref.read(attendanceProvider);

    final existingRecord = allRecords.where((record) =>
        record.staffId == staffId &&
        record.date.year == normalizedDate.year &&
        record.date.month == normalizedDate.month &&
        record.date.day == normalizedDate.day).firstOrNull;

    if (existingRecord != null) {
      await _repository.updateAttendance(existingRecord.copyWith(status: status));
    } else {
      await _repository.saveAttendance(
        AttendanceRecord(
          id: '', // Will be generated by Firestore
          staffId: staffId,
          date: normalizedDate,
          status: status,
        ),
      );
    }
  }

  Future<void> markLeaveForRange(String staffId, DateTime startDate, DateTime endDate) async {
    DateTime current = DateTime(startDate.year, startDate.month, startDate.day);
    final end = DateTime(endDate.year, endDate.month, endDate.day);

    final List<AttendanceRecord> leaveRecords = [];

    while (current.compareTo(end) <= 0) {
      leaveRecords.add(
        AttendanceRecord(
          id: '', // Will be generated by Firestore batch
          staffId: staffId,
          date: current,
          status: AttendanceStatus.leave,
        ),
      );
      current = DateTime(current.year, current.month, current.day + 1);
    }
    
    if (leaveRecords.isNotEmpty) {
      await _repository.saveAttendanceBatch(leaveRecords);
    }
  }
}

final attendanceControllerProvider = Provider<AttendanceController>((ref) {
  final repository = ref.watch(attendanceRepositoryProvider);
  return AttendanceController(ref, repository);
});

// Backward compatible provider for UI
final attendanceProvider = Provider<List<AttendanceRecord>>((ref) {
  final asyncRecords = ref.watch(attendanceStreamProvider);
  return asyncRecords.value ?? [];
});

// A derived provider to get today's attendance records easily
final todaysAttendanceProvider = Provider<List<AttendanceRecord>>((ref) {
  final records = ref.watch(attendanceProvider);
  final today = ref.watch(todayProvider);
  return records
      .where(
        (r) =>
            r.date.year == today.year &&
            r.date.month == today.month &&
            r.date.day == today.day,
      )
      .toList();
});
